# Generated by Django 4.2.5 on 2023-09-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
