# Generated by Django 4.2.5 on 2023-09-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0002_alter_surfboard_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
