# Generated by Django 4.2.5 on 2023-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0004_alter_surfboard_fin_style_alter_surfboard_fin_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='style',
            field=models.CharField(choices=[('fish', 'Fish'), ('twin', 'Twin'), ('round', 'Round'), ('asym', 'Asym'), ('swallow-tail', 'Swallow-tail'), ('pin tail', 'Pin tail'), ('squash', 'Squash'), ('mini-simmons', 'Mini-simmons'), ('other', 'Other')], max_length=100, verbose_name='Board Style'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
