# Generated by Django 4.2.5 on 2023-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0006_alter_surfboard_style_alter_surfboard_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='fin_style',
            field=models.CharField(choices=[('Single fin', 'Single'), ('Twin', 'Twin'), ('Thruster', 'Thruster'), ('Quad', 'Quad'), ('Finless', 'Finless'), ('Other', 'Other')], max_length=20, verbose_name='Fin Style'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='fin_system',
            field=models.CharField(choices=[('Fcs1', 'FCS 1'), ('Fcs2', 'FCS 2'), ('Futures', 'Futures'), ('Other', 'Other')], max_length=20, verbose_name='Fin System'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='style',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Twin', 'Twin'), ('Round', 'Round'), ('Asym', 'Asym'), ('Swallow-tail', 'Swallow-tail'), ('Pin tail', 'Pin tail'), ('Squash', 'Squash'), ('Mini-simmons', 'Mini-simmons'), ('Other', 'Other')], max_length=100, verbose_name='Tail Style'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='thickness',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='type',
            field=models.CharField(choices=[('Shortboard', 'Shortboard'), ('Mid-length', 'Mid-length'), ('Longboard', 'Longboard'), ('Other', 'Other')], max_length=20, verbose_name='Board Type'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Volume, L'),
        ),
        migrations.AlterField(
            model_name='surfboard',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
