# Generated by Django 4.2.5 on 2023-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0009_alter_surfboard_currently_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfboard',
            name='style',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Round', 'Round'), ('Asym', 'Asym'), ('Swallow-tail', 'Swallow-tail'), ('Pin tail', 'Pin tail'), ('Squash', 'Squash'), ('Other', 'Other')], max_length=100, verbose_name='Tail Style'),
        ),
    ]
