# Generated by Django 4.2.5 on 2023-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0013_alter_reservation_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
