# Generated by Django 4.2.5 on 2023-09-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfboards', '0015_alter_reservation_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfboard',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='surfboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surfboards', to='surfboards.surfboard'),
        ),
    ]
